# Generated by Django 3.2.9 on 2021-11-17 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0019_merge_0016_profile_visited_0018_listdescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='messages')),
                ('type', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=100)),
                ('nameChanged', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to='profiles.Profile')),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', max_length=60)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatLog', to='chat.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='profiles.profile')),
            ],
            options={
                'ordering': ('creationDate',),
            },
        ),
    ]
