# Generated by Django 3.2.9 on 2021-11-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_merge_0016_profile_visited_0018_listdescriptions'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='members', to='profiles.Profile'),
        ),
    ]
