# Generated by Django 3.2.8 on 2021-11-02 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
