# Generated by Django 3.2.8 on 2021-11-02 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_messages_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 21, 18, 59, 874902, tzinfo=utc)),
        ),
    ]
