# Generated by Django 3.2.8 on 2021-11-05 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_listdescriptions'),
        ('chat', '0006_alter_messages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='profiles.profile')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='profiles.profile')),
            ],
            options={
                'ordering': ('creationDate',),
            },
        ),
    ]
