# Generated by Django 3.2.8 on 2021-11-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_lastsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastsent',
            name='messages',
            field=models.TextField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='messages',
            name='messages',
            field=models.TextField(default='', max_length=60),
        ),
    ]
