# Generated by Django 3.2.8 on 2021-11-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='name',
            field=models.TextField(default='', max_length=60),
        ),
    ]
