# Generated by Django 3.2.8 on 2021-11-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_groupchat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(default='', max_length=60)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.groupchat')),
            ],
            options={
                'ordering': ('creationDate',),
            },
        ),
    ]
