# Generated by Django 3.2.8 on 2021-11-11 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_merge_0016_profile_visited_0018_listdescriptions'),
        ('chat', '0012_auto_20211111_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gc_message', to='chat.groupchatmessages'),
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='users',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='users',
            field=models.ManyToManyField(related_name='gc_users', to='profiles.Profile'),
        ),
    ]
