# Generated by Django 3.2.8 on 2021-11-11 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_groupchat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gc_message', to='chat.groupchatmessages'),
        ),
    ]
