# Generated by Django 3.2.9 on 2021-11-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_merge_0016_profile_visited_0018_listdescriptions'),
        ('chat', '0015_alter_groupchat_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=100)),
                ('nameChanged', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to='profiles.Profile')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.RemoveField(
            model_name='groupchatmessages',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='lastsent',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='lastsent',
            name='user_2',
        ),
        migrations.RemoveField(
            model_name='lastsentgroup',
            name='group',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='profile',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
        migrations.DeleteModel(
            name='GroupChatMessages',
        ),
        migrations.DeleteModel(
            name='LastSent',
        ),
        migrations.DeleteModel(
            name='LastSentGroup',
        ),
        migrations.AddField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatLog', to='chat.chat'),
        ),
    ]
