# Generated by Django 3.2.7 on 2021-10-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='emoji',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.originemoji'),
        ),
    ]
