# Generated by Django 3.2.7 on 2021-10-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_alter_comment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(),
        ),
    ]
