# Generated by Django 3.2.7 on 2021-11-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_alter_comment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.DeleteModel(
            name='OriginEmoji',
        ),
    ]
