# Generated by Django 3.2.7 on 2021-09-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210919_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='from_location',
            field=models.TextField(default='', max_length=30),
        ),
    ]
