# Generated by Django 3.2.7 on 2021-09-27 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_profile_savedlocation_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlocation',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.location'),
        ),
    ]
