# Generated by Django 3.2.8 on 2021-10-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_list_locationlist'),
    ]

    operations = [
    ]
