# Generated by Django 3.2.7 on 2021-10-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_list_locationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlocation',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedLocations', to='profiles.locationlist'),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
