# Generated by Django 3.2.8 on 2021-10-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.TextField(default='', max_length=50),
        ),
    ]
