# Generated by Django 3.2.7 on 2021-10-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20211004_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlocation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.location'),
        ),
    ]
