# Generated by Django 3.2.8 on 2021-10-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_savedlocation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlocation',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.locationlist'),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.location'),
        ),
    ]
