# Generated by Django 3.2.8 on 2021-10-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20211011_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlocation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.location'),
        ),
    ]
