# Generated by Django 3.2.7 on 2021-10-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_background'),
        ('profiles', '0013_alter_savedlocation_name'),
    ]

    operations = [
    ]
