# Generated by Django 3.2.7 on 2021-10-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_merge_20211017_2054'),
        ('profiles', '0014_shareablelink'),
    ]

    operations = [
    ]
