# Generated by Django 3.2.8 on 2021-10-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_merge_0014_merge_20211017_2054_0014_shareablelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visited',
            field=models.TextField(default='', max_length=50),
        ),
    ]
