# Generated by Django 3.2.7 on 2021-10-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_listdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListDescription',
        ),
    ]
