# Generated by Django 3.2.8 on 2021-11-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_visited'),
        ('profiles', '0018_listdescriptions'),
    ]

    operations = [
    ]
