# Generated by Django 3.2.9 on 2021-12-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_merge_0016_profile_visited_0018_listdescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareableListPageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('shareable_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.shareablelink')),
            ],
        ),
    ]
