# Generated by Django 3.2.9 on 2021-12-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20211203_2049'),
        ('profiles', '0020_shareablelistpagecomment'),
    ]

    operations = [
    ]
