from django.urls import path

from .views import (
AddDescriptionView,
AddVisitedView,
DelDescriptionView,
DeleteVisitedView,
EditDescriptionView,
ChangeVisitedView,
GetProfileView, 
ChangeLocationView,
GetVisitedDataView, 
SearchUserView, 
AddListView, 
DeleteListView, 
AddLocationListView,
AddLocationView,
DelLocationView,
DeleteLocationListView, 
GetAllProfilesView, 
GetUserListsView, 
GetListDataView, 
GetSetShareableLink,
GetShareableLinkList,
ChangeBackgroundView,
AddDescriptionView,
DelDescriptionView,
EditDescriptionView,
GetDescriptionView,
AddSharedListCommentView,
GetSharedListCommentView,
ChangeUserNameView,
ChangeProfileLocationView,
ResetView
)

app_name = "profiles"

urlpatterns = [
    path('get_profile/', GetProfileView.as_view()),
    path('change_location/', ChangeLocationView.as_view()),
    path('search_user/', SearchUserView.as_view()),
    path('add_list/', AddListView.as_view()),
    path('delete_list/', DeleteListView.as_view()),
    path('add_location_list/', AddLocationListView.as_view()),
    path('delete_location_list/', DeleteLocationListView.as_view()),
    path('search_filter/', GetAllProfilesView.as_view()),
    path('get_lists/', GetUserListsView.as_view()),
    path('get_list_data/', GetListDataView.as_view()),
    path('add_location/', AddLocationView.as_view()),
    path('del_location/', DelLocationView.as_view()),
    path('change_background/', ChangeBackgroundView.as_view()),
    path('change_visited/', ChangeVisitedView.as_view()),
    path('shareable_link/',GetSetShareableLink.as_view()),
    path('get_shareable_contents/', GetShareableLinkList.as_view()),
    path('add_description/', AddDescriptionView.as_view()),
    path('del_description/', DelDescriptionView.as_view()),
    path('edit_description/', EditDescriptionView.as_view()),
    path('get_description/', GetDescriptionView.as_view()),
    path('add_visited_list/', AddVisitedView.as_view()),
    path('get_visited_data/', DeleteVisitedView.as_view()),
    path('delete_visited_data', GetVisitedDataView.as_view()),
    path ('add_sharedlist_comments/', AddSharedListCommentView.as_view()), 
    path ('get_sharedlist_comments/', GetSharedListCommentView.as_view()),
    path('change_username/', ChangeUserNameView.as_view()), 
    path('change_profile_location/', ChangeProfileLocationView.as_view()), 
    path ('reset/', ResetView.as_view())
]